# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-Daemon-MPG321
version:      0.001
version_from: lib/Audio/Daemon/MPG321.pm
installdirs:  site
requires:
    Audio::Play::MPG321:           0.003

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
